Remove redundant type checks
laminas/laminas-ci-matrix-action pull request #78
Opened 2022-03-03 09:37 UTC by boesing

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Due to the fact that this action validates the projects `.laminas-ci.json` with the `laminas-ci.schema.json` file, we do not have to verify types in some codepaths anymore.

2022-03-03 09:45 UTC, Ocramius requested changes

2022-03-03 09:45 UTC, Ocramius commented on src/additional-checks.js
> -    if (typeof checkConfig !== 'object' || checkConfig === null) {
We should really write some typescript :D

2022-03-03 09:45 UTC, Ocramius commented on src/additional-checks.js
> -    if (checkConfig.name === undefined || checkConfig.job === undefined) {
Shouldn't we validate this? Nothing in the type declaration above says that `checkConfig.job` is required

2022-03-03 09:45 UTC, Ocramius commented on src/additional-checks.js
> -    if (typeof checkConfig.job !== 'object' || checkConfig.job === null) {
Shouldn't we validate this? Nothing in the type declaration above says that `checkConfig.job` must be an `object`

2022-03-03 10:23 UTC, boesing commented on src/additional-checks.js
> -    if (typeof checkConfig !== 'object' || checkConfig === null) {
I am not that familiar with typescript yet.

Do you have examples on how to achieve all these optional things in typescript/javascript?
I guess if we have to convert this action to typescript, I rather keep the redundant checks as I am definitely no expert in this at all.

2022-03-03 11:14 UTC, boesing commented
@Ocramius Would `eslint` check would be suitable for this?

I could give this a try to provide at least a little CI pipeline for this repository. I've started in #62 but I wanted to use our current CI pipeline. Maybe that was the wrong way since testing a repository with the repository might lead to unexpected issues.

Could start adding `eslint` and then extend with integration tests which verify the return values for different project setups.

2022-03-03 11:24 UTC, Ocramius commented
`eslint` would certainly be a first step, yes.

Overall, this codebase is growing, and I'm concerned that it could grow in an uncontrolled way, which would make it hard to manage. Anything that helps us keeping complexity in check will help, and types are a must, if we don't have tests.

2022-03-03 11:25 UTC, Ocramius commented on src/additional-checks.js
> -    if (typeof checkConfig !== 'object' || checkConfig === null) {
Changing to typescript here is obviously out of scope for this patch. As for the definition, I would expect something more precise than `{Object}` as input definition for `checkConfig`, but I don't know much about JS docblock syntax :thinking:

2022-03-16 22:31 UTC, boesing commented
#82 introduces ESLint and I am currently working on porting to typescript.
Closing this in favor of typescript.

2022-03-16 22:31 UTC, closed without merging